# Generated by Django 5.0.4 on 2024-08-24 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('hr', '0002_alter_candidateapplication_yearofexp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplication'),
        ),
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
